version: "3.9"
services:

  {{ role }}-garlicoin-exporter:
    container_name: {{ role }}-garlicoin-exporter
    ports:
      - {{ monitor_port }}:9439
    environment:
      - rpchost={{ role }}-garlicoin
      - rpcuser={{ rpc_username }}
      - rpcpassword={{ rpc_password }}
      - rpcport={{ rpc_port }}
    links:
      - {{ role }}-garlicoin
    restart: always
